### ISSUE TITLE
fix vertical serifs in YOPQ YSV*

### ISSUE THREAD

**Issue by gferreira** [gferreira/amstelvar-avar2#14]
currently in YSV* min the width of the vertical serifs (XSV*) is also changing (to preserve the serif shape). I realize now that this was am mistake, parameters should remain independent. 

__to do: in YSV* min, the width of vertical serifs must stay unchanged in relation to default__

(illustration coming soon :)

**Comment by gferreira** [comment]
vertical serifs in 'E' fixed in YOPQ YSVU min bdbacd14a0a1fa8bfa0ef5d4be51b3503f419e49

- YSVU does not change XSVU 
- YOPQ does not change YSVU

![Screenshot 2024-02-01 at 07 33 33](https://github.com/gferreira/amstelvar-avar2/assets/62717/665ca615-f7ca-4f7f-ae8d-79d95cc721a8)

![Screenshot 2024-02-01 at 07 33 54](https://github.com/gferreira/amstelvar-avar2/assets/62717/973c1810-7eb0-4f6e-af60-0a0ba4bbb97d)

**Comment by gferreira2** [comment]
also fixed in C F L S T Z c r s z
