### ISSUE TITLE
XOUC in default

### ISSUE THREAD

**Issue by irenevlachou** [gferreira/amstelvar-avar2#15]
XOUC measurement seems to be a unit thinner in "E" and the ink trap one unit small than the one in "F".
 I'm fixing the design and putting the old "E" in the background layer.
Let me know if that was on purpose and I'll change to back.
Work done in default, XOPQmin and YOPQmin.

![XOUC_F](https://github.com/gferreira/amstelvar-avar2/assets/11784297/8fbff468-e492-4993-8b51-c2e54d437445)
![XOUC_E](https://github.com/gferreira/amstelvar-avar2/assets/11784297/0a254e6a-cee6-40ee-a54d-64c23addf006)
![XOUC_H](https://github.com/gferreira/amstelvar-avar2/assets/11784297/1ee13c36-8d98-450a-b8cd-7cd9a02474c1)

**Comment by gferreira2** [comment]
if this change is done in the default, it should also to be done in all other sources which use the default shape.

in Fontra it is possible to move points in multiple sources at the same time. you can click on the eye icon to make individual layers visible, and on the pen icon to make them editable:

![Screenshot 2024-02-04 at 00 56 53](https://github.com/gferreira/amstelvar-avar2/assets/150602003/aba10544-a83d-4e18-a0fe-4766d3fcde03)

I don't really mind the 1 unit difference at this stage though, there are probably many of those. we can search for them in a systematic way.

**Comment by irenevlachou** [comment]
cool! I did't update it and it's true there are a couple of them. Maybe we do it at the end.
