### ISSUE TITLE
New avar2 testing needs

### ISSUE THREAD

**Issue by dberlow** [gferreira/amstelvar-avar2#9]
An expanded json file is requested with all the Blends of our alpha designspace.

For each size master, there are an addition four sides and four corners, ie. 9 locations per size.
There are three size masters.
That’s 27 locations.

Please make such a file and let me know if there are any ?

**Comment by gferreira** [comment]
- blends file, designspaces and variable fonts updated with all 27 blends for `opsz` `wght` `wdth`
- `XTSP` replaced with `XUCS` — see #10
